### ISSUE TITLE
How to evaluate the model with different combination of missing modalities?

### ISSUE THREAD

**Issue by YaoZhang93** [dyh127/RFNet#2]
Hi Yuhang, 

How to evaluate the model with different combination of missing modalities?

Best,
Yao

**Comment by dyh127** [comment]
Hi Yao,

We evaluate all combinations of missing modalities by random setting features of missing modalities to zero tensors.

The evaluation code can be referred to https://github.com/dyh127/RFNet/blob/main/train.py#L234. 

Best regards,
Yuhang

**Comment by YaoZhang93** [comment]
Got it. Thanks :)
